// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSesEventDestination struct {
	meta_v1.TypeMeta   `json:",inline"`
	meta_v1.ObjectMeta `json:"metadata,omitempty"`
	Spec               AwsSesEventDestinationSpec `json:"spec"`
}

type AwsSesEventDestinationSpec struct {
	Name                  string                                          `json:"name"`
	ConfigurationSetName  string                                          `json:"configuration_set_name"`
	Enabled               bool                                            `json:"enabled"`
	MatchingTypes         string                                          `json:"matching_types"`
	CloudwatchDestination AwsSesEventDestinationSpecCloudwatchDestination `json:"cloudwatch_destination"`
	KinesisDestination    AwsSesEventDestinationSpecKinesisDestination    `json:"kinesis_destination"`
	SnsDestination        AwsSesEventDestinationSpecSnsDestination        `json:"sns_destination"`
}

type AwsSesEventDestinationSpecCloudwatchDestination struct {
	ValueSource   string `json:"value_source"`
	DefaultValue  string `json:"default_value"`
	DimensionName string `json:"dimension_name"`
}

type AwsSesEventDestinationSpecKinesisDestination struct {
	StreamArn string `json:"stream_arn"`
	RoleArn   string `json:"role_arn"`
}

type AwsSesEventDestinationSpecSnsDestination struct {
	TopicArn string `json:"topic_arn"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSesEventDestinationList struct {
	meta_v1.TypeMeta `json:",inline"`
	meta_v1.ListMeta `json:"metadata,omitempty"`
	Items            []AwsSesEventDestination `json:"items"`
}
