// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDefaultVpcDhcpOptions struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsDefaultVpcDhcpOptionsSpec `json"spec"`
}

type AwsDefaultVpcDhcpOptionsSpec struct {
	DomainName         string            `json:"domain_name"`
	DomainNameServers  string            `json:"domain_name_servers"`
	NtpServers         string            `json:"ntp_servers"`
	NetbiosNodeType    string            `json:"netbios_node_type"`
	NetbiosNameServers []string          `json:"netbios_name_servers"`
	Tags               map[string]string `json:"tags"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDefaultVpcDhcpOptionsList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsDefaultVpcDhcpOptions `json"items"`
}
