// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsEmrCluster struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsEmrClusterSpec `json"spec"`
}

type AwsEmrClusterSpec struct {
	MasterInstanceType          string                                `json:"master_instance_type"`
	TerminationProtection       bool                                  `json:"termination_protection"`
	ReleaseLabel                string                                `json:"release_label"`
	LogUri                      string                                `json:"log_uri"`
	MasterPublicDns             string                                `json:"master_public_dns"`
	Ec2Attributes               []AwsEmrClusterSpecEc2Attributes      `json:"ec2_attributes"`
	BootstrapAction             AwsEmrClusterSpecBootstrapAction      `json:"bootstrap_action"`
	Step                        []AwsEmrClusterSpecStep               `json:"step"`
	Configurations              string                                `json:"configurations"`
	ServiceRole                 string                                `json:"service_role"`
	ScaleDownBehavior           string                                `json:"scale_down_behavior"`
	AutoscalingRole             string                                `json:"autoscaling_role"`
	EbsRootVolumeSize           int                                   `json:"ebs_root_volume_size"`
	ClusterState                string                                `json:"cluster_state"`
	Applications                string                                `json:"applications"`
	KeepJobFlowAliveWhenNoSteps bool                                  `json:"keep_job_flow_alive_when_no_steps"`
	KerberosAttributes          []AwsEmrClusterSpecKerberosAttributes `json:"kerberos_attributes"`
	InstanceGroup               AwsEmrClusterSpecInstanceGroup        `json:"instance_group"`
	SecurityConfiguration       string                                `json:"security_configuration"`
	VisibleToAllUsers           bool                                  `json:"visible_to_all_users"`
	Name                        string                                `json:"name"`
	CoreInstanceType            string                                `json:"core_instance_type"`
	CoreInstanceCount           int                                   `json:"core_instance_count"`
	Tags                        map[string]string                     `json:"tags"`
	CustomAmiId                 string                                `json:"custom_ami_id"`
}

type AwsEmrClusterSpecEc2Attributes struct {
	EmrManagedMasterSecurityGroup  string `json:"emr_managed_master_security_group"`
	EmrManagedSlaveSecurityGroup   string `json:"emr_managed_slave_security_group"`
	InstanceProfile                string `json:"instance_profile"`
	ServiceAccessSecurityGroup     string `json:"service_access_security_group"`
	KeyName                        string `json:"key_name"`
	SubnetId                       string `json:"subnet_id"`
	AdditionalMasterSecurityGroups string `json:"additional_master_security_groups"`
	AdditionalSlaveSecurityGroups  string `json:"additional_slave_security_groups"`
}

type AwsEmrClusterSpecBootstrapAction struct {
	Name string   `json:"name"`
	Path string   `json:"path"`
	Args []string `json:"args"`
}

type AwsEmrClusterSpecStep struct {
	ActionOnFailure string                               `json:"action_on_failure"`
	HadoopJarStep   []AwsEmrClusterSpecStepHadoopJarStep `json:"hadoop_jar_step"`
	Name            string                               `json:"name"`
}

type AwsEmrClusterSpecStepHadoopJarStep struct {
	Args       []string          `json:"args"`
	Jar        string            `json:"jar"`
	MainClass  string            `json:"main_class"`
	Properties map[string]string `json:"properties"`
}

type AwsEmrClusterSpecKerberosAttributes struct {
	CrossRealmTrustPrincipalPassword string `json:"cross_realm_trust_principal_password"`
	KdcAdminPassword                 string `json:"kdc_admin_password"`
	Realm                            string `json:"realm"`
	AdDomainJoinPassword             string `json:"ad_domain_join_password"`
	AdDomainJoinUser                 string `json:"ad_domain_join_user"`
}

type AwsEmrClusterSpecInstanceGroup struct {
	BidPrice          string                                  `json:"bid_price"`
	EbsConfig         AwsEmrClusterSpecInstanceGroupEbsConfig `json:"ebs_config"`
	InstanceCount     int                                     `json:"instance_count"`
	AutoscalingPolicy string                                  `json:"autoscaling_policy"`
	InstanceRole      string                                  `json:"instance_role"`
	InstanceType      string                                  `json:"instance_type"`
	Name              string                                  `json:"name"`
}

type AwsEmrClusterSpecInstanceGroupEbsConfig struct {
	Iops               int    `json:"iops"`
	Size               int    `json:"size"`
	Type               string `json:"type"`
	VolumesPerInstance int    `json:"volumes_per_instance"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsEmrClusterList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsEmrCluster `json"items"`
}
