// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsCodebuildProject struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsCodebuildProjectSpec `json"spec"`
}

type AwsCodebuildProjectSpec struct {
	BuildTimeout  int                                `json:"build_timeout"`
	VpcConfig     []AwsCodebuildProjectSpecVpcConfig `json:"vpc_config"`
	Cache         []AwsCodebuildProjectSpecCache     `json:"cache"`
	EncryptionKey string                             `json:"encryption_key"`
	Environment   AwsCodebuildProjectSpecEnvironment `json:"environment"`
	ServiceRole   string                             `json:"service_role"`
	Source        AwsCodebuildProjectSpecSource      `json:"source"`
	Timeout       int                                `json:"timeout"`
	Artifacts     AwsCodebuildProjectSpecArtifacts   `json:"artifacts"`
	Description   string                             `json:"description"`
	Name          string                             `json:"name"`
	Tags          map[string]string                  `json:"tags"`
}

type AwsCodebuildProjectSpecVpcConfig struct {
	VpcId            string `json:"vpc_id"`
	Subnets          string `json:"subnets"`
	SecurityGroupIds string `json:"security_group_ids"`
}

type AwsCodebuildProjectSpecCache struct {
	Type     string `json:"type"`
	Location string `json:"location"`
}

type AwsCodebuildProjectSpecEnvironment struct {
	Type                string                                                  `json:"type"`
	PrivilegedMode      bool                                                    `json:"privileged_mode"`
	ComputeType         string                                                  `json:"compute_type"`
	EnvironmentVariable []AwsCodebuildProjectSpecEnvironmentEnvironmentVariable `json:"environment_variable"`
	Image               string                                                  `json:"image"`
}

type AwsCodebuildProjectSpecEnvironmentEnvironmentVariable struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type AwsCodebuildProjectSpecSource struct {
	Location  string                            `json:"location"`
	Type      string                            `json:"type"`
	Auth      AwsCodebuildProjectSpecSourceAuth `json:"auth"`
	Buildspec string                            `json:"buildspec"`
}

type AwsCodebuildProjectSpecSourceAuth struct {
	Type     string `json:"type"`
	Resource string `json:"resource"`
}

type AwsCodebuildProjectSpecArtifacts struct {
	NamespaceType string `json:"namespace_type"`
	Packaging     string `json:"packaging"`
	Path          string `json:"path"`
	Type          string `json:"type"`
	Name          string `json:"name"`
	Location      string `json:"location"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsCodebuildProjectList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsCodebuildProject `json"items"`
}
