// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsGlacierVault struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsGlacierVaultSpec `json"spec"`
}

type AwsGlacierVaultSpec struct {
	Name         string                            `json:"name"`
	Location     string                            `json:"location"`
	Arn          string                            `json:"arn"`
	AccessPolicy string                            `json:"access_policy"`
	Notification []AwsGlacierVaultSpecNotification `json:"notification"`
	Tags         map[string]string                 `json:"tags"`
}

type AwsGlacierVaultSpecNotification struct {
	Events   string `json:"events"`
	SnsTopic string `json:"sns_topic"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsGlacierVaultList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsGlacierVault `json"items"`
}
