// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsRoute53HealthCheck struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsRoute53HealthCheckSpec `json"spec"`
}

type AwsRoute53HealthCheckSpec struct {
	EnableSni                    bool              `json:"enable_sni"`
	Regions                      string            `json:"regions"`
	ResourcePath                 string            `json:"resource_path"`
	SearchString                 string            `json:"search_string"`
	CloudwatchAlarmName          string            `json:"cloudwatch_alarm_name"`
	CloudwatchAlarmRegion        string            `json:"cloudwatch_alarm_region"`
	InsufficientDataHealthStatus string            `json:"insufficient_data_health_status"`
	Tags                         map[string]string `json:"tags"`
	Type                         string            `json:"type"`
	InvertHealthcheck            bool              `json:"invert_healthcheck"`
	ChildHealthThreshold         int               `json:"child_health_threshold"`
	ReferenceName                string            `json:"reference_name"`
	RequestInterval              int               `json:"request_interval"`
	MeasureLatency               bool              `json:"measure_latency"`
	Fqdn                         string            `json:"fqdn"`
	Port                         int               `json:"port"`
	ChildHealthchecks            string            `json:"child_healthchecks"`
	FailureThreshold             int               `json:"failure_threshold"`
	IpAddress                    string            `json:"ip_address"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsRoute53HealthCheckList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsRoute53HealthCheck `json"items"`
}
