// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSqsQueue struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsSqsQueueSpec `json"spec"`
}

type AwsSqsQueueSpec struct {
	MaxMessageSize               int               `json:"max_message_size"`
	VisibilityTimeoutSeconds     int               `json:"visibility_timeout_seconds"`
	ContentBasedDeduplication    bool              `json:"content_based_deduplication"`
	KmsMasterKeyId               string            `json:"kms_master_key_id"`
	KmsDataKeyReusePeriodSeconds int               `json:"kms_data_key_reuse_period_seconds"`
	Name                         string            `json:"name"`
	RedrivePolicy                string            `json:"redrive_policy"`
	NamePrefix                   string            `json:"name_prefix"`
	MessageRetentionSeconds      int               `json:"message_retention_seconds"`
	ReceiveWaitTimeSeconds       int               `json:"receive_wait_time_seconds"`
	Policy                       string            `json:"policy"`
	Arn                          string            `json:"arn"`
	FifoQueue                    bool              `json:"fifo_queue"`
	Tags                         map[string]string `json:"tags"`
	DelaySeconds                 int               `json:"delay_seconds"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSqsQueueList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsSqsQueue `json"items"`
}
