// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksPhpAppLayer struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsOpsworksPhpAppLayerSpec `json"spec"`
}

type AwsOpsworksPhpAppLayerSpec struct {
	AutoAssignPublicIps      bool                                `json:"auto_assign_public_ips"`
	ElasticLoadBalancer      string                              `json:"elastic_load_balancer"`
	CustomSetupRecipes       []string                            `json:"custom_setup_recipes"`
	CustomDeployRecipes      []string                            `json:"custom_deploy_recipes"`
	UseEbsOptimizedInstances bool                                `json:"use_ebs_optimized_instances"`
	EbsVolume                AwsOpsworksPhpAppLayerSpecEbsVolume `json:"ebs_volume"`
	Name                     string                              `json:"name"`
	StackId                  string                              `json:"stack_id"`
	CustomConfigureRecipes   []string                            `json:"custom_configure_recipes"`
	CustomUndeployRecipes    []string                            `json:"custom_undeploy_recipes"`
	CustomShutdownRecipes    []string                            `json:"custom_shutdown_recipes"`
	CustomSecurityGroupIds   string                              `json:"custom_security_group_ids"`
	CustomJson               string                              `json:"custom_json"`
	DrainElbOnShutdown       bool                                `json:"drain_elb_on_shutdown"`
	SystemPackages           string                              `json:"system_packages"`
	AutoAssignElasticIps     bool                                `json:"auto_assign_elastic_ips"`
	AutoHealing              bool                                `json:"auto_healing"`
	CustomInstanceProfileArn string                              `json:"custom_instance_profile_arn"`
	InstallUpdatesOnBoot     bool                                `json:"install_updates_on_boot"`
	InstanceShutdownTimeout  int                                 `json:"instance_shutdown_timeout"`
}

type AwsOpsworksPhpAppLayerSpecEbsVolume struct {
	Iops          int    `json:"iops"`
	MountPoint    string `json:"mount_point"`
	NumberOfDisks int    `json:"number_of_disks"`
	RaidLevel     string `json:"raid_level"`
	Size          int    `json:"size"`
	Type          string `json:"type"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksPhpAppLayerList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsOpsworksPhpAppLayer `json"items"`
}
