// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsCognitoUserPoolClient struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsCognitoUserPoolClientSpec `json"spec"`
}

type AwsCognitoUserPoolClientSpec struct {
	ReadAttributes                  string   `json:"read_attributes"`
	AllowedOauthFlows               string   `json:"allowed_oauth_flows"`
	WriteAttributes                 string   `json:"write_attributes"`
	AllowedOauthFlowsUserPoolClient bool     `json:"allowed_oauth_flows_user_pool_client"`
	SupportedIdentityProviders      []string `json:"supported_identity_providers"`
	UserPoolId                      string   `json:"user_pool_id"`
	ExplicitAuthFlows               string   `json:"explicit_auth_flows"`
	RefreshTokenValidity            int      `json:"refresh_token_validity"`
	AllowedOauthScopes              string   `json:"allowed_oauth_scopes"`
	CallbackUrls                    []string `json:"callback_urls"`
	DefaultRedirectUri              string   `json:"default_redirect_uri"`
	LogoutUrls                      []string `json:"logout_urls"`
	Name                            string   `json:"name"`
	GenerateSecret                  bool     `json:"generate_secret"`
	ClientSecret                    string   `json:"client_secret"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsCognitoUserPoolClientList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsCognitoUserPoolClient `json"items"`
}
