// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsApiGatewayDomainName struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsApiGatewayDomainNameSpec `json"spec"`
}

type AwsApiGatewayDomainNameSpec struct {
	DomainName            string `json:"domain_name"`
	CertificateArn        string `json:"certificate_arn"`
	CloudfrontZoneId      string `json:"cloudfront_zone_id"`
	CertificatePrivateKey string `json:"certificate_private_key"`
	CloudfrontDomainName  string `json:"cloudfront_domain_name"`
	CertificateUploadDate string `json:"certificate_upload_date"`
	CertificateBody       string `json:"certificate_body"`
	CertificateChain      string `json:"certificate_chain"`
	CertificateName       string `json:"certificate_name"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsApiGatewayDomainNameList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsApiGatewayDomainName `json"items"`
}
