// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSecretsmanagerSecret struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsSecretsmanagerSecretSpec `json"spec"`
}

type AwsSecretsmanagerSecretSpec struct {
	RotationRules        []AwsSecretsmanagerSecretSpecRotationRules `json:"rotation_rules"`
	Tags                 map[string]string                          `json:"tags"`
	Arn                  string                                     `json:"arn"`
	RotationEnabled      bool                                       `json:"rotation_enabled"`
	RotationLambdaArn    string                                     `json:"rotation_lambda_arn"`
	RecoveryWindowInDays int                                        `json:"recovery_window_in_days"`
	Description          string                                     `json:"description"`
	KmsKeyId             string                                     `json:"kms_key_id"`
	Name                 string                                     `json:"name"`
}

type AwsSecretsmanagerSecretSpecRotationRules struct {
	AutomaticallyAfterDays int `json:"automatically_after_days"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSecretsmanagerSecretList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsSecretsmanagerSecret `json"items"`
}
