// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksApplication struct {
	meta_v1.TypeMeta   `json:",inline"`
	meta_v1.ObjectMeta `json:"metadata,omitempty"`
	Spec               AwsOpsworksApplicationSpec `json:"spec"`
}

type AwsOpsworksApplicationSpec struct {
	DocumentRoot           string                                       `json:"document_root"`
	AutoBundleOnDeploy     string                                       `json:"auto_bundle_on_deploy"`
	Description            string                                       `json:"description"`
	SslConfiguration       []AwsOpsworksApplicationSpecSslConfiguration `json:"ssl_configuration"`
	Name                   string                                       `json:"name"`
	StackId                string                                       `json:"stack_id"`
	EnableSsl              bool                                         `json:"enable_ssl"`
	Type                   string                                       `json:"type"`
	DataSourceDatabaseName string                                       `json:"data_source_database_name"`
	AppSource              []AwsOpsworksApplicationSpecAppSource        `json:"app_source"`
	Environment            AwsOpsworksApplicationSpecEnvironment        `json:"environment"`
	ShortName              string                                       `json:"short_name"`
	RailsEnv               string                                       `json:"rails_env"`
	DataSourceArn          string                                       `json:"data_source_arn"`
	Domains                []string                                     `json:"domains"`
	AwsFlowRubySettings    string                                       `json:"aws_flow_ruby_settings"`
	DataSourceType         string                                       `json:"data_source_type"`
}

type AwsOpsworksApplicationSpecSslConfiguration struct {
	Certificate string `json:"certificate"`
	PrivateKey  string `json:"private_key"`
	Chain       string `json:"chain"`
}

type AwsOpsworksApplicationSpecAppSource struct {
	Revision string `json:"revision"`
	SshKey   string `json:"ssh_key"`
	Type     string `json:"type"`
	Url      string `json:"url"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type AwsOpsworksApplicationSpecEnvironment struct {
	Key    string `json:"key"`
	Value  string `json:"value"`
	Secure bool   `json:"secure"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksApplicationList struct {
	meta_v1.TypeMeta `json:",inline"`
	meta_v1.ListMeta `json:"metadata,omitempty"`
	Items            []AwsOpsworksApplication `json:"items"`
}
