// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAutoscalingGroup struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsAutoscalingGroupSpec `json"spec"`
}

type AwsAutoscalingGroupSpec struct {
	MinElbCapacity         int                                         `json:"min_elb_capacity"`
	DefaultCooldown        int                                         `json:"default_cooldown"`
	AvailabilityZones      string                                      `json:"availability_zones"`
	TerminationPolicies    []string                                    `json:"termination_policies"`
	Tag                    AwsAutoscalingGroupSpecTag                  `json:"tag"`
	ServiceLinkedRoleArn   string                                      `json:"service_linked_role_arn"`
	Tags                   []map[string]string                         `json:"tags"`
	LaunchConfiguration    string                                      `json:"launch_configuration"`
	LaunchTemplate         []AwsAutoscalingGroupSpecLaunchTemplate     `json:"launch_template"`
	MaxSize                int                                         `json:"max_size"`
	ForceDelete            bool                                        `json:"force_delete"`
	SuspendedProcesses     string                                      `json:"suspended_processes"`
	Arn                    string                                      `json:"arn"`
	WaitForElbCapacity     int                                         `json:"wait_for_elb_capacity"`
	NamePrefix             string                                      `json:"name_prefix"`
	LoadBalancers          string                                      `json:"load_balancers"`
	DesiredCapacity        int                                         `json:"desired_capacity"`
	HealthCheckGracePeriod int                                         `json:"health_check_grace_period"`
	TargetGroupArns        string                                      `json:"target_group_arns"`
	InitialLifecycleHook   AwsAutoscalingGroupSpecInitialLifecycleHook `json:"initial_lifecycle_hook"`
	Name                   string                                      `json:"name"`
	HealthCheckType        string                                      `json:"health_check_type"`
	ProtectFromScaleIn     bool                                        `json:"protect_from_scale_in"`
	MinSize                int                                         `json:"min_size"`
	WaitForCapacityTimeout string                                      `json:"wait_for_capacity_timeout"`
	EnabledMetrics         string                                      `json:"enabled_metrics"`
	PlacementGroup         string                                      `json:"placement_group"`
	VpcZoneIdentifier      string                                      `json:"vpc_zone_identifier"`
	MetricsGranularity     string                                      `json:"metrics_granularity"`
}

type AwsAutoscalingGroupSpecTag struct {
	Value             string `json:"value"`
	PropagateAtLaunch bool   `json:"propagate_at_launch"`
	Key               string `json:"key"`
}

type AwsAutoscalingGroupSpecLaunchTemplate struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

type AwsAutoscalingGroupSpecInitialLifecycleHook struct {
	NotificationTargetArn string `json:"notification_target_arn"`
	RoleArn               string `json:"role_arn"`
	Name                  string `json:"name"`
	DefaultResult         string `json:"default_result"`
	HeartbeatTimeout      int    `json:"heartbeat_timeout"`
	LifecycleTransition   string `json:"lifecycle_transition"`
	NotificationMetadata  string `json:"notification_metadata"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAutoscalingGroupList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsAutoscalingGroup `json"items"`
}
