// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsBudgetsBudget struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsBudgetsBudgetSpec `json"spec"`
}

type AwsBudgetsBudgetSpec struct {
	CostFilters     map[string]string               `json:"cost_filters"`
	NamePrefix      string                          `json:"name_prefix"`
	BudgetType      string                          `json:"budget_type"`
	TimePeriodStart string                          `json:"time_period_start"`
	TimePeriodEnd   string                          `json:"time_period_end"`
	TimeUnit        string                          `json:"time_unit"`
	AccountId       string                          `json:"account_id"`
	Name            string                          `json:"name"`
	LimitAmount     string                          `json:"limit_amount"`
	LimitUnit       string                          `json:"limit_unit"`
	CostTypes       []AwsBudgetsBudgetSpecCostTypes `json:"cost_types"`
}

type AwsBudgetsBudgetSpecCostTypes struct {
	IncludeCredit            bool `json:"include_credit"`
	IncludeDiscount          bool `json:"include_discount"`
	IncludeOtherSubscription bool `json:"include_other_subscription"`
	IncludeRecurring         bool `json:"include_recurring"`
	IncludeSupport           bool `json:"include_support"`
	IncludeTax               bool `json:"include_tax"`
	IncludeUpfront           bool `json:"include_upfront"`
	UseAmortized             bool `json:"use_amortized"`
	UseBlended               bool `json:"use_blended"`
	IncludeRefund            bool `json:"include_refund"`
	IncludeSubscription      bool `json:"include_subscription"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsBudgetsBudgetList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsBudgetsBudget `json"items"`
}
