// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksStack struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsOpsworksStackSpec `json"spec"`
}

type AwsOpsworksStackSpec struct {
	CustomJson                  string                                      `json:"custom_json"`
	DefaultSshKeyName           string                                      `json:"default_ssh_key_name"`
	HostnameTheme               string                                      `json:"hostname_theme"`
	Tags                        map[string]string                           `json:"tags"`
	Arn                         string                                      `json:"arn"`
	CustomCookbooksSource       []AwsOpsworksStackSpecCustomCookbooksSource `json:"custom_cookbooks_source"`
	BerkshelfVersion            string                                      `json:"berkshelf_version"`
	UseOpsworksSecurityGroups   bool                                        `json:"use_opsworks_security_groups"`
	AgentVersion                string                                      `json:"agent_version"`
	ManageBerkshelf             bool                                        `json:"manage_berkshelf"`
	ServiceRoleArn              string                                      `json:"service_role_arn"`
	Color                       string                                      `json:"color"`
	ConfigurationManagerName    string                                      `json:"configuration_manager_name"`
	ConfigurationManagerVersion string                                      `json:"configuration_manager_version"`
	DefaultRootDeviceType       string                                      `json:"default_root_device_type"`
	DefaultSubnetId             string                                      `json:"default_subnet_id"`
	Name                        string                                      `json:"name"`
	Region                      string                                      `json:"region"`
	StackEndpoint               string                                      `json:"stack_endpoint"`
	UseCustomCookbooks          bool                                        `json:"use_custom_cookbooks"`
	VpcId                       string                                      `json:"vpc_id"`
	DefaultOs                   string                                      `json:"default_os"`
	DefaultInstanceProfileArn   string                                      `json:"default_instance_profile_arn"`
	DefaultAvailabilityZone     string                                      `json:"default_availability_zone"`
}

type AwsOpsworksStackSpecCustomCookbooksSource struct {
	Revision string `json:"revision"`
	SshKey   string `json:"ssh_key"`
	Type     string `json:"type"`
	Url      string `json:"url"`
	Username string `json:"username"`
	Password string `json:"password"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksStackList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsOpsworksStack `json"items"`
}
