// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsKmsKey struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsKmsKeySpec `json"spec"`
}

type AwsKmsKeySpec struct {
	DeletionWindowInDays int               `json:"deletion_window_in_days"`
	KeyId                string            `json:"key_id"`
	Description          string            `json:"description"`
	Policy               string            `json:"policy"`
	EnableKeyRotation    bool              `json:"enable_key_rotation"`
	Tags                 map[string]string `json:"tags"`
	Arn                  string            `json:"arn"`
	KeyUsage             string            `json:"key_usage"`
	IsEnabled            bool              `json:"is_enabled"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsKmsKeyList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsKmsKey `json"items"`
}
