// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAlb struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsAlbSpec `json"spec"`
}

type AwsAlbSpec struct {
	ZoneId                       string                  `json:"zone_id"`
	ArnSuffix                    string                  `json:"arn_suffix"`
	SecurityGroups               string                  `json:"security_groups"`
	SubnetMapping                AwsAlbSpecSubnetMapping `json:"subnet_mapping"`
	IdleTimeout                  int                     `json:"idle_timeout"`
	IpAddressType                string                  `json:"ip_address_type"`
	Arn                          string                  `json:"arn"`
	Subnets                      string                  `json:"subnets"`
	AccessLogs                   []AwsAlbSpecAccessLogs  `json:"access_logs"`
	EnableHttp2                  bool                    `json:"enable_http2"`
	VpcId                        string                  `json:"vpc_id"`
	NamePrefix                   string                  `json:"name_prefix"`
	LoadBalancerType             string                  `json:"load_balancer_type"`
	Tags                         map[string]string       `json:"tags"`
	Name                         string                  `json:"name"`
	Internal                     bool                    `json:"internal"`
	EnableDeletionProtection     bool                    `json:"enable_deletion_protection"`
	EnableCrossZoneLoadBalancing bool                    `json:"enable_cross_zone_load_balancing"`
	DnsName                      string                  `json:"dns_name"`
}

type AwsAlbSpecSubnetMapping struct {
	SubnetId     string `json:"subnet_id"`
	AllocationId string `json:"allocation_id"`
}

type AwsAlbSpecAccessLogs struct {
	Bucket  string `json:"bucket"`
	Prefix  string `json:"prefix"`
	Enabled bool   `json:"enabled"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAlbList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsAlb `json"items"`
}
