// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsWafregionalRule struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsWafregionalRuleSpec `json"spec"`
}

type AwsWafregionalRuleSpec struct {
	Name       string                          `json:"name"`
	MetricName string                          `json:"metric_name"`
	Predicate  AwsWafregionalRuleSpecPredicate `json:"predicate"`
}

type AwsWafregionalRuleSpecPredicate struct {
	DataId  string `json:"data_id"`
	Type    string `json:"type"`
	Negated bool   `json:"negated"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsWafregionalRuleList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsWafregionalRule `json"items"`
}
