// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDmsReplicationInstance struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsDmsReplicationInstanceSpec `json"spec"`
}

type AwsDmsReplicationInstanceSpec struct {
	VpcSecurityGroupIds           string            `json:"vpc_security_group_ids"`
	AllocatedStorage              int               `json:"allocated_storage"`
	ReplicationSubnetGroupId      string            `json:"replication_subnet_group_id"`
	Tags                          map[string]string `json:"tags"`
	ReplicationInstancePrivateIps []string          `json:"replication_instance_private_ips"`
	ReplicationInstancePublicIps  []string          `json:"replication_instance_public_ips"`
	ApplyImmediately              bool              `json:"apply_immediately"`
	KmsKeyArn                     string            `json:"kms_key_arn"`
	PubliclyAccessible            bool              `json:"publicly_accessible"`
	ReplicationInstanceId         string            `json:"replication_instance_id"`
	EngineVersion                 string            `json:"engine_version"`
	MultiAz                       bool              `json:"multi_az"`
	ReplicationInstanceArn        string            `json:"replication_instance_arn"`
	ReplicationInstanceClass      string            `json:"replication_instance_class"`
	AutoMinorVersionUpgrade       bool              `json:"auto_minor_version_upgrade"`
	AvailabilityZone              string            `json:"availability_zone"`
	PreferredMaintenanceWindow    string            `json:"preferred_maintenance_window"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDmsReplicationInstanceList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsDmsReplicationInstance `json"items"`
}
