// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsNetworkAcl struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsNetworkAclSpec `json"spec"`
}

type AwsNetworkAclSpec struct {
	Ingress   AwsNetworkAclSpecIngress `json:"ingress"`
	Egress    AwsNetworkAclSpecEgress  `json:"egress"`
	Tags      map[string]string        `json:"tags"`
	VpcId     string                   `json:"vpc_id"`
	SubnetId  string                   `json:"subnet_id"`
	SubnetIds string                   `json:"subnet_ids"`
}

type AwsNetworkAclSpecIngress struct {
	ToPort        int    `json:"to_port"`
	RuleNo        int    `json:"rule_no"`
	Ipv6CidrBlock string `json:"ipv6_cidr_block"`
	IcmpCode      int    `json:"icmp_code"`
	FromPort      int    `json:"from_port"`
	Protocol      string `json:"protocol"`
	CidrBlock     string `json:"cidr_block"`
	IcmpType      int    `json:"icmp_type"`
	Action        string `json:"action"`
}

type AwsNetworkAclSpecEgress struct {
	ToPort        int    `json:"to_port"`
	RuleNo        int    `json:"rule_no"`
	Protocol      string `json:"protocol"`
	Ipv6CidrBlock string `json:"ipv6_cidr_block"`
	IcmpType      int    `json:"icmp_type"`
	FromPort      int    `json:"from_port"`
	Action        string `json:"action"`
	CidrBlock     string `json:"cidr_block"`
	IcmpCode      int    `json:"icmp_code"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsNetworkAclList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsNetworkAcl `json"items"`
}
