// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsEcsService struct {
	meta_v1.TypeMeta   `json:",inline"`
	meta_v1.ObjectMeta `json:"metadata,omitempty"`
	Spec               AwsEcsServiceSpec `json:"spec"`
}

type AwsEcsServiceSpec struct {
	LoadBalancer                    AwsEcsServiceSpecLoadBalancer               `json:"load_balancer"`
	LaunchType                      string                                      `json:"launch_type"`
	DeploymentMaximumPercent        int                                         `json:"deployment_maximum_percent"`
	IamRole                         string                                      `json:"iam_role"`
	DeploymentMinimumHealthyPercent int                                         `json:"deployment_minimum_healthy_percent"`
	NetworkConfiguration            []AwsEcsServiceSpecNetworkConfiguration     `json:"network_configuration"`
	OrderedPlacementStrategy        []AwsEcsServiceSpecOrderedPlacementStrategy `json:"ordered_placement_strategy"`
	PlacementConstraints            AwsEcsServiceSpecPlacementConstraints       `json:"placement_constraints"`
	ServiceRegistries               AwsEcsServiceSpecServiceRegistries          `json:"service_registries"`
	Name                            string                                      `json:"name"`
	DesiredCount                    int                                         `json:"desired_count"`
	HealthCheckGracePeriodSeconds   int                                         `json:"health_check_grace_period_seconds"`
	PlacementStrategy               AwsEcsServiceSpecPlacementStrategy          `json:"placement_strategy"`
	Cluster                         string                                      `json:"cluster"`
	TaskDefinition                  string                                      `json:"task_definition"`
}

type AwsEcsServiceSpecLoadBalancer struct {
	ElbName        string `json:"elb_name"`
	TargetGroupArn string `json:"target_group_arn"`
	ContainerName  string `json:"container_name"`
	ContainerPort  int    `json:"container_port"`
}

type AwsEcsServiceSpecNetworkConfiguration struct {
	SecurityGroups string `json:"security_groups"`
	Subnets        string `json:"subnets"`
	AssignPublicIp bool   `json:"assign_public_ip"`
}

type AwsEcsServiceSpecOrderedPlacementStrategy struct {
	Type  string `json:"type"`
	Field string `json:"field"`
}

type AwsEcsServiceSpecPlacementConstraints struct {
	Type       string `json:"type"`
	Expression string `json:"expression"`
}

type AwsEcsServiceSpecServiceRegistries struct {
	Port        int    `json:"port"`
	RegistryArn string `json:"registry_arn"`
}

type AwsEcsServiceSpecPlacementStrategy struct {
	Type  string `json:"type"`
	Field string `json:"field"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsEcsServiceList struct {
	meta_v1.TypeMeta `json:",inline"`
	meta_v1.ListMeta `json:"metadata,omitempty"`
	Items            []AwsEcsService `json:"items"`
}
