// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAmiFromInstance struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsAmiFromInstanceSpec `json"spec"`
}

type AwsAmiFromInstanceSpec struct {
	RamdiskId             string                                     `json:"ramdisk_id"`
	VirtualizationType    string                                     `json:"virtualization_type"`
	ManageEbsSnapshots    bool                                       `json:"manage_ebs_snapshots"`
	SnapshotWithoutReboot bool                                       `json:"snapshot_without_reboot"`
	Description           string                                     `json:"description"`
	Tags                  map[string]string                          `json:"tags"`
	SourceInstanceId      string                                     `json:"source_instance_id"`
	Architecture          string                                     `json:"architecture"`
	RootSnapshotId        string                                     `json:"root_snapshot_id"`
	SriovNetSupport       string                                     `json:"sriov_net_support"`
	EbsBlockDevice        AwsAmiFromInstanceSpecEbsBlockDevice       `json:"ebs_block_device"`
	EphemeralBlockDevice  AwsAmiFromInstanceSpecEphemeralBlockDevice `json:"ephemeral_block_device"`
	ImageLocation         string                                     `json:"image_location"`
	KernelId              string                                     `json:"kernel_id"`
	Name                  string                                     `json:"name"`
	RootDeviceName        string                                     `json:"root_device_name"`
}

type AwsAmiFromInstanceSpecEbsBlockDevice struct {
	SnapshotId          string `json:"snapshot_id"`
	VolumeSize          int    `json:"volume_size"`
	VolumeType          string `json:"volume_type"`
	DeleteOnTermination bool   `json:"delete_on_termination"`
	DeviceName          string `json:"device_name"`
	Encrypted           bool   `json:"encrypted"`
	Iops                int    `json:"iops"`
}

type AwsAmiFromInstanceSpecEphemeralBlockDevice struct {
	VirtualName string `json:"virtual_name"`
	DeviceName  string `json:"device_name"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAmiFromInstanceList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsAmiFromInstance `json"items"`
}
