// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDaxCluster struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsDaxClusterSpec `json"spec"`
}

type AwsDaxClusterSpec struct {
	AvailabilityZones     string                   `json:"availability_zones"`
	NotificationTopicArn  string                   `json:"notification_topic_arn"`
	Tags                  map[string]string        `json:"tags"`
	ConfigurationEndpoint string                   `json:"configuration_endpoint"`
	ClusterName           string                   `json:"cluster_name"`
	NodeType              string                   `json:"node_type"`
	Description           string                   `json:"description"`
	SecurityGroupIds      string                   `json:"security_group_ids"`
	ClusterAddress        string                   `json:"cluster_address"`
	Nodes                 []AwsDaxClusterSpecNodes `json:"nodes"`
	IamRoleArn            string                   `json:"iam_role_arn"`
	ReplicationFactor     int                      `json:"replication_factor"`
	ParameterGroupName    string                   `json:"parameter_group_name"`
	SubnetGroupName       string                   `json:"subnet_group_name"`
	Port                  int                      `json:"port"`
	Arn                   string                   `json:"arn"`
	MaintenanceWindow     string                   `json:"maintenance_window"`
}

type AwsDaxClusterSpecNodes struct {
	Id               string `json:"id"`
	Address          string `json:"address"`
	Port             int    `json:"port"`
	AvailabilityZone string `json:"availability_zone"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDaxClusterList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsDaxCluster `json"items"`
}
