// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsEbsSnapshot struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsEbsSnapshotSpec `json"spec"`
}

type AwsEbsSnapshotSpec struct {
	KmsKeyId            string            `json:"kms_key_id"`
	VolumeId            string            `json:"volume_id"`
	Encrypted           bool              `json:"encrypted"`
	OwnerAlias          string            `json:"owner_alias"`
	VolumeSize          int               `json:"volume_size"`
	DataEncryptionKeyId string            `json:"data_encryption_key_id"`
	Tags                map[string]string `json:"tags"`
	Description         string            `json:"description"`
	OwnerId             string            `json:"owner_id"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsEbsSnapshotList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsEbsSnapshot `json"items"`
}
