// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsApiGatewayAuthorizer struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsApiGatewayAuthorizerSpec `json"spec"`
}

type AwsApiGatewayAuthorizerSpec struct {
	RestApiId                    string `json:"rest_api_id"`
	IdentityValidationExpression string `json:"identity_validation_expression"`
	ProviderArns                 string `json:"provider_arns"`
	IdentitySource               string `json:"identity_source"`
	Name                         string `json:"name"`
	Type                         string `json:"type"`
	AuthorizerCredentials        string `json:"authorizer_credentials"`
	AuthorizerResultTtlInSeconds int    `json:"authorizer_result_ttl_in_seconds"`
	AuthorizerUri                string `json:"authorizer_uri"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsApiGatewayAuthorizerList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsApiGatewayAuthorizer `json"items"`
}
