// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsApiGatewayIntegration struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsApiGatewayIntegrationSpec `json"spec"`
}

type AwsApiGatewayIntegrationSpec struct {
	Credentials             string            `json:"credentials"`
	IntegrationHttpMethod   string            `json:"integration_http_method"`
	RequestParametersInJson string            `json:"request_parameters_in_json"`
	CacheKeyParameters      string            `json:"cache_key_parameters"`
	ResourceId              string            `json:"resource_id"`
	HttpMethod              string            `json:"http_method"`
	Uri                     string            `json:"uri"`
	PassthroughBehavior     string            `json:"passthrough_behavior"`
	ConnectionId            string            `json:"connection_id"`
	RequestTemplates        map[string]string `json:"request_templates"`
	RequestParameters       map[string]string `json:"request_parameters"`
	ContentHandling         string            `json:"content_handling"`
	CacheNamespace          string            `json:"cache_namespace"`
	RestApiId               string            `json:"rest_api_id"`
	Type                    string            `json:"type"`
	ConnectionType          string            `json:"connection_type"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsApiGatewayIntegrationList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsApiGatewayIntegration `json"items"`
}
