// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDirectoryServiceDirectory struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsDirectoryServiceDirectorySpec `json"spec"`
}

type AwsDirectoryServiceDirectorySpec struct {
	ShortName       string                                            `json:"short_name"`
	DnsIpAddresses  string                                            `json:"dns_ip_addresses"`
	Type            string                                            `json:"type"`
	Edition         string                                            `json:"edition"`
	Password        string                                            `json:"password"`
	Alias           string                                            `json:"alias"`
	ConnectSettings []AwsDirectoryServiceDirectorySpecConnectSettings `json:"connect_settings"`
	EnableSso       bool                                              `json:"enable_sso"`
	AccessUrl       string                                            `json:"access_url"`
	Name            string                                            `json:"name"`
	Size            string                                            `json:"size"`
	Description     string                                            `json:"description"`
	Tags            map[string]string                                 `json:"tags"`
	VpcSettings     []AwsDirectoryServiceDirectorySpecVpcSettings     `json:"vpc_settings"`
	SecurityGroupId string                                            `json:"security_group_id"`
}

type AwsDirectoryServiceDirectorySpecConnectSettings struct {
	CustomerUsername string `json:"customer_username"`
	CustomerDnsIps   string `json:"customer_dns_ips"`
	SubnetIds        string `json:"subnet_ids"`
	VpcId            string `json:"vpc_id"`
}

type AwsDirectoryServiceDirectorySpecVpcSettings struct {
	SubnetIds string `json:"subnet_ids"`
	VpcId     string `json:"vpc_id"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDirectoryServiceDirectoryList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsDirectoryServiceDirectory `json"items"`
}
