// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksApplication struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsOpsworksApplicationSpec `json"spec"`
}

type AwsOpsworksApplicationSpec struct {
	Environment            AwsOpsworksApplicationSpecEnvironment        `json:"environment"`
	EnableSsl              bool                                         `json:"enable_ssl"`
	AutoBundleOnDeploy     string                                       `json:"auto_bundle_on_deploy"`
	DataSourceType         string                                       `json:"data_source_type"`
	Domains                []string                                     `json:"domains"`
	DocumentRoot           string                                       `json:"document_root"`
	AwsFlowRubySettings    string                                       `json:"aws_flow_ruby_settings"`
	DataSourceDatabaseName string                                       `json:"data_source_database_name"`
	DataSourceArn          string                                       `json:"data_source_arn"`
	Description            string                                       `json:"description"`
	SslConfiguration       []AwsOpsworksApplicationSpecSslConfiguration `json:"ssl_configuration"`
	Name                   string                                       `json:"name"`
	ShortName              string                                       `json:"short_name"`
	RailsEnv               string                                       `json:"rails_env"`
	AppSource              []AwsOpsworksApplicationSpecAppSource        `json:"app_source"`
	Type                   string                                       `json:"type"`
	StackId                string                                       `json:"stack_id"`
}

type AwsOpsworksApplicationSpecEnvironment struct {
	Key    string `json:"key"`
	Value  string `json:"value"`
	Secure bool   `json:"secure"`
}

type AwsOpsworksApplicationSpecSslConfiguration struct {
	PrivateKey  string `json:"private_key"`
	Chain       string `json:"chain"`
	Certificate string `json:"certificate"`
}

type AwsOpsworksApplicationSpecAppSource struct {
	Type     string `json:"type"`
	Url      string `json:"url"`
	Username string `json:"username"`
	Password string `json:"password"`
	Revision string `json:"revision"`
	SshKey   string `json:"ssh_key"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsOpsworksApplicationList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsOpsworksApplication `json"items"`
}
