// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsGlueCatalogTable struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsGlueCatalogTableSpec `json"spec"`
}

type AwsGlueCatalogTableSpec struct {
	CatalogId         string                                     `json:"catalog_id"`
	Description       string                                     `json:"description"`
	Parameters        map[string]string                          `json:"parameters"`
	Retention         int                                        `json:"retention"`
	StorageDescriptor []AwsGlueCatalogTableSpecStorageDescriptor `json:"storage_descriptor"`
	ViewOriginalText  string                                     `json:"view_original_text"`
	ViewExpandedText  string                                     `json:"view_expanded_text"`
	DatabaseName      string                                     `json:"database_name"`
	Name              string                                     `json:"name"`
	Owner             string                                     `json:"owner"`
	PartitionKeys     []AwsGlueCatalogTableSpecPartitionKeys     `json:"partition_keys"`
	TableType         string                                     `json:"table_type"`
}

type AwsGlueCatalogTableSpecStorageDescriptor struct {
	Compressed             bool                                                  `json:"compressed"`
	NumberOfBuckets        int                                                   `json:"number_of_buckets"`
	OutputFormat           string                                                `json:"output_format"`
	Parameters             map[string]string                                     `json:"parameters"`
	SerDeInfo              []AwsGlueCatalogTableSpecStorageDescriptorSerDeInfo   `json:"ser_de_info"`
	SortColumns            []AwsGlueCatalogTableSpecStorageDescriptorSortColumns `json:"sort_columns"`
	StoredAsSubDirectories bool                                                  `json:"stored_as_sub_directories"`
	Columns                []AwsGlueCatalogTableSpecStorageDescriptorColumns     `json:"columns"`
	InputFormat            string                                                `json:"input_format"`
	Location               string                                                `json:"location"`
	SkewedInfo             []AwsGlueCatalogTableSpecStorageDescriptorSkewedInfo  `json:"skewed_info"`
	BucketColumns          []string                                              `json:"bucket_columns"`
}

type AwsGlueCatalogTableSpecStorageDescriptorSerDeInfo struct {
	SerializationLibrary string            `json:"serialization_library"`
	Name                 string            `json:"name"`
	Parameters           map[string]string `json:"parameters"`
}

type AwsGlueCatalogTableSpecStorageDescriptorSortColumns struct {
	Column    string `json:"column"`
	SortOrder int    `json:"sort_order"`
}

type AwsGlueCatalogTableSpecStorageDescriptorColumns struct {
	Comment string `json:"comment"`
	Name    string `json:"name"`
	Type    string `json:"type"`
}

type AwsGlueCatalogTableSpecStorageDescriptorSkewedInfo struct {
	SkewedColumnNames             []string          `json:"skewed_column_names"`
	SkewedColumnValues            []string          `json:"skewed_column_values"`
	SkewedColumnValueLocationMaps map[string]string `json:"skewed_column_value_location_maps"`
}

type AwsGlueCatalogTableSpecPartitionKeys struct {
	Type    string `json:"type"`
	Comment string `json:"comment"`
	Name    string `json:"name"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsGlueCatalogTableList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsGlueCatalogTable `json"items"`
}
