// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsVpc struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsVpcSpec `json"spec"`
}

type AwsVpcSpec struct {
	Tags                         map[string]string `json:"tags"`
	CidrBlock                    string            `json:"cidr_block"`
	DefaultNetworkAclId          string            `json:"default_network_acl_id"`
	DefaultSecurityGroupId       string            `json:"default_security_group_id"`
	DefaultRouteTableId          string            `json:"default_route_table_id"`
	EnableDnsHostnames           bool              `json:"enable_dns_hostnames"`
	AssignGeneratedIpv6CidrBlock bool              `json:"assign_generated_ipv6_cidr_block"`
	MainRouteTableId             string            `json:"main_route_table_id"`
	DhcpOptionsId                string            `json:"dhcp_options_id"`
	Ipv6CidrBlock                string            `json:"ipv6_cidr_block"`
	EnableDnsSupport             bool              `json:"enable_dns_support"`
	EnableClassiclink            bool              `json:"enable_classiclink"`
	EnableClassiclinkDnsSupport  bool              `json:"enable_classiclink_dns_support"`
	Ipv6AssociationId            string            `json:"ipv6_association_id"`
	InstanceTenancy              string            `json:"instance_tenancy"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsVpcList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsVpc `json"items"`
}
