// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsIamOpenidConnectProvider struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsIamOpenidConnectProviderSpec `json"spec"`
}

type AwsIamOpenidConnectProviderSpec struct {
	Arn            string   `json:"arn"`
	Url            string   `json:"url"`
	ClientIdList   []string `json:"client_id_list"`
	ThumbprintList []string `json:"thumbprint_list"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsIamOpenidConnectProviderList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsIamOpenidConnectProvider `json"items"`
}
