// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsIotThingType struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsIotThingTypeSpec `json"spec"`
}

type AwsIotThingTypeSpec struct {
	Properties []AwsIotThingTypeSpecProperties `json:"properties"`
	Deprecated bool                            `json:"deprecated"`
	Arn        string                          `json:"arn"`
	Name       string                          `json:"name"`
}

type AwsIotThingTypeSpecProperties struct {
	Description          string `json:"description"`
	SearchableAttributes string `json:"searchable_attributes"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsIotThingTypeList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsIotThingType `json"items"`
}
