// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDbSnapshot struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsDbSnapshotSpec `json"spec"`
}

type AwsDbSnapshotSpec struct {
	Engine                     string `json:"engine"`
	SourceRegion               string `json:"source_region"`
	DbSnapshotArn              string `json:"db_snapshot_arn"`
	OptionGroupName            string `json:"option_group_name"`
	SnapshotType               string `json:"snapshot_type"`
	Status                     string `json:"status"`
	StorageType                string `json:"storage_type"`
	DbSnapshotIdentifier       string `json:"db_snapshot_identifier"`
	AvailabilityZone           string `json:"availability_zone"`
	Iops                       int    `json:"iops"`
	KmsKeyId                   string `json:"kms_key_id"`
	Port                       int    `json:"port"`
	DbInstanceIdentifier       string `json:"db_instance_identifier"`
	Encrypted                  bool   `json:"encrypted"`
	EngineVersion              string `json:"engine_version"`
	LicenseModel               string `json:"license_model"`
	SourceDbSnapshotIdentifier string `json:"source_db_snapshot_identifier"`
	VpcId                      string `json:"vpc_id"`
	AllocatedStorage           int    `json:"allocated_storage"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsDbSnapshotList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsDbSnapshot `json"items"`
}
