// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsRdsCluster struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsRdsClusterSpec `json"spec"`
}

type AwsRdsClusterSpec struct {
	DbSubnetGroupName                string                      `json:"db_subnet_group_name"`
	S3Import                         []AwsRdsClusterSpecS3Import `json:"s3_import"`
	MasterPassword                   string                      `json:"master_password"`
	SnapshotIdentifier               string                      `json:"snapshot_identifier"`
	SourceRegion                     string                      `json:"source_region"`
	ClusterIdentifierPrefix          string                      `json:"cluster_identifier_prefix"`
	ClusterMembers                   string                      `json:"cluster_members"`
	VpcSecurityGroupIds              string                      `json:"vpc_security_group_ids"`
	KmsKeyId                         string                      `json:"kms_key_id"`
	ReplicationSourceIdentifier      string                      `json:"replication_source_identifier"`
	AvailabilityZones                string                      `json:"availability_zones"`
	DbClusterParameterGroupName      string                      `json:"db_cluster_parameter_group_name"`
	HostedZoneId                     string                      `json:"hosted_zone_id"`
	SkipFinalSnapshot                bool                        `json:"skip_final_snapshot"`
	PreferredBackupWindow            string                      `json:"preferred_backup_window"`
	DatabaseName                     string                      `json:"database_name"`
	Tags                             map[string]string           `json:"tags"`
	IamDatabaseAuthenticationEnabled bool                        `json:"iam_database_authentication_enabled"`
	ClusterResourceId                string                      `json:"cluster_resource_id"`
	ClusterIdentifier                string                      `json:"cluster_identifier"`
	StorageEncrypted                 bool                        `json:"storage_encrypted"`
	MasterUsername                   string                      `json:"master_username"`
	PreferredMaintenanceWindow       string                      `json:"preferred_maintenance_window"`
	IamRoles                         string                      `json:"iam_roles"`
	BackupRetentionPeriod            int                         `json:"backup_retention_period"`
	ReaderEndpoint                   string                      `json:"reader_endpoint"`
	Engine                           string                      `json:"engine"`
	EngineVersion                    string                      `json:"engine_version"`
	FinalSnapshotIdentifier          string                      `json:"final_snapshot_identifier"`
	ApplyImmediately                 bool                        `json:"apply_immediately"`
	Endpoint                         string                      `json:"endpoint"`
	Port                             int                         `json:"port"`
}

type AwsRdsClusterSpecS3Import struct {
	IngestionRole       string `json:"ingestion_role"`
	SourceEngine        string `json:"source_engine"`
	SourceEngineVersion string `json:"source_engine_version"`
	BucketName          string `json:"bucket_name"`
	BucketPrefix        string `json:"bucket_prefix"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsRdsClusterList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsRdsCluster `json"items"`
}
