// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAutoscalingPolicy struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsAutoscalingPolicySpec `json"spec"`
}

type AwsAutoscalingPolicySpec struct {
	AdjustmentType              string                                                `json:"adjustment_type"`
	EstimatedInstanceWarmup     int                                                   `json:"estimated_instance_warmup"`
	MetricAggregationType       string                                                `json:"metric_aggregation_type"`
	Arn                         string                                                `json:"arn"`
	Name                        string                                                `json:"name"`
	Cooldown                    int                                                   `json:"cooldown"`
	MinAdjustmentMagnitude      int                                                   `json:"min_adjustment_magnitude"`
	MinAdjustmentStep           int                                                   `json:"min_adjustment_step"`
	ScalingAdjustment           int                                                   `json:"scaling_adjustment"`
	StepAdjustment              AwsAutoscalingPolicySpecStepAdjustment                `json:"step_adjustment"`
	TargetTrackingConfiguration []AwsAutoscalingPolicySpecTargetTrackingConfiguration `json:"target_tracking_configuration"`
	AutoscalingGroupName        string                                                `json:"autoscaling_group_name"`
	PolicyType                  string                                                `json:"policy_type"`
}

type AwsAutoscalingPolicySpecStepAdjustment struct {
	MetricIntervalLowerBound string `json:"metric_interval_lower_bound"`
	MetricIntervalUpperBound string `json:"metric_interval_upper_bound"`
	ScalingAdjustment        int    `json:"scaling_adjustment"`
}

type AwsAutoscalingPolicySpecTargetTrackingConfiguration struct {
	PredefinedMetricSpecification []AwsAutoscalingPolicySpecTargetTrackingConfigurationPredefinedMetricSpecification `json:"predefined_metric_specification"`
	CustomizedMetricSpecification []AwsAutoscalingPolicySpecTargetTrackingConfigurationCustomizedMetricSpecification `json:"customized_metric_specification"`
	TargetValue                   float64                                                                            `json:"target_value"`
	DisableScaleIn                bool                                                                               `json:"disable_scale_in"`
}

type AwsAutoscalingPolicySpecTargetTrackingConfigurationPredefinedMetricSpecification struct {
	PredefinedMetricType string `json:"predefined_metric_type"`
	ResourceLabel        string `json:"resource_label"`
}

type AwsAutoscalingPolicySpecTargetTrackingConfigurationCustomizedMetricSpecification struct {
	MetricDimension []AwsAutoscalingPolicySpecTargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension `json:"metric_dimension"`
	MetricName      string                                                                                            `json:"metric_name"`
	Namespace       string                                                                                            `json:"namespace"`
	Statistic       string                                                                                            `json:"statistic"`
	Unit            string                                                                                            `json:"unit"`
}

type AwsAutoscalingPolicySpecTargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsAutoscalingPolicyList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsAutoscalingPolicy `json"items"`
}
