// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsElasticacheCluster struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsElasticacheClusterSpec `json"spec"`
}

type AwsElasticacheClusterSpec struct {
	SecurityGroupNames     string                                `json:"security_group_names"`
	MaintenanceWindow      string                                `json:"maintenance_window"`
	Tags                   map[string]string                     `json:"tags"`
	ConfigurationEndpoint  string                                `json:"configuration_endpoint"`
	CacheNodes             []AwsElasticacheClusterSpecCacheNodes `json:"cache_nodes"`
	EngineVersion          string                                `json:"engine_version"`
	SnapshotArns           string                                `json:"snapshot_arns"`
	SnapshotWindow         string                                `json:"snapshot_window"`
	SnapshotName           string                                `json:"snapshot_name"`
	Port                   int                                   `json:"port"`
	NotificationTopicArn   string                                `json:"notification_topic_arn"`
	NumCacheNodes          int                                   `json:"num_cache_nodes"`
	SubnetGroupName        string                                `json:"subnet_group_name"`
	SnapshotRetentionLimit int                                   `json:"snapshot_retention_limit"`
	ApplyImmediately       bool                                  `json:"apply_immediately"`
	AzMode                 string                                `json:"az_mode"`
	ClusterAddress         string                                `json:"cluster_address"`
	ReplicationGroupId     string                                `json:"replication_group_id"`
	AvailabilityZones      string                                `json:"availability_zones"`
	NodeType               string                                `json:"node_type"`
	Engine                 string                                `json:"engine"`
	ParameterGroupName     string                                `json:"parameter_group_name"`
	SecurityGroupIds       string                                `json:"security_group_ids"`
	ClusterId              string                                `json:"cluster_id"`
	AvailabilityZone       string                                `json:"availability_zone"`
}

type AwsElasticacheClusterSpecCacheNodes struct {
	Id               string `json:"id"`
	Address          string `json:"address"`
	Port             int    `json:"port"`
	AvailabilityZone string `json:"availability_zone"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsElasticacheClusterList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsElasticacheCluster `json"items"`
}
