// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsIamInstanceProfile struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsIamInstanceProfileSpec `json"spec"`
}

type AwsIamInstanceProfileSpec struct {
	CreateDate string `json:"create_date"`
	UniqueId   string `json:"unique_id"`
	Name       string `json:"name"`
	NamePrefix string `json:"name_prefix"`
	Path       string `json:"path"`
	Roles      string `json:"roles"`
	Role       string `json:"role"`
	Arn        string `json:"arn"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsIamInstanceProfileList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsIamInstanceProfile `json"items"`
}
