// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsLightsailInstance struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsLightsailInstanceSpec `json"spec"`
}

type AwsLightsailInstanceSpec struct {
	PrivateIpAddress string `json:"private_ip_address"`
	AvailabilityZone string `json:"availability_zone"`
	RamSize          int    `json:"ram_size"`
	Arn              string `json:"arn"`
	UserData         string `json:"user_data"`
	CpuCount         int    `json:"cpu_count"`
	Ipv6Address      string `json:"ipv6_address"`
	IsStaticIp       bool   `json:"is_static_ip"`
	PublicIpAddress  string `json:"public_ip_address"`
	Name             string `json:"name"`
	KeyPairName      string `json:"key_pair_name"`
	CreatedAt        string `json:"created_at"`
	Username         string `json:"username"`
	BlueprintId      string `json:"blueprint_id"`
	BundleId         string `json:"bundle_id"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsLightsailInstanceList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsLightsailInstance `json"items"`
}
