// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsWafregionalWebAcl struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsWafregionalWebAclSpec `json"spec"`
}

type AwsWafregionalWebAclSpec struct {
	Name          string                                  `json:"name"`
	DefaultAction []AwsWafregionalWebAclSpecDefaultAction `json:"default_action"`
	MetricName    string                                  `json:"metric_name"`
	Rule          AwsWafregionalWebAclSpecRule            `json:"rule"`
}

type AwsWafregionalWebAclSpecDefaultAction struct {
	Type string `json:"type"`
}

type AwsWafregionalWebAclSpecRule struct {
	Priority int                                  `json:"priority"`
	RuleId   string                               `json:"rule_id"`
	Action   []AwsWafregionalWebAclSpecRuleAction `json:"action"`
}

type AwsWafregionalWebAclSpecRuleAction struct {
	Type string `json:"type"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsWafregionalWebAclList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsWafregionalWebAcl `json"items"`
}
