// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSsmMaintenanceWindowTask struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Spec               AwsSsmMaintenanceWindowTaskSpec `json"spec"`
}

type AwsSsmMaintenanceWindowTaskSpec struct {
	Priority       int                                             `json:"priority"`
	TaskParameters []AwsSsmMaintenanceWindowTaskSpecTaskParameters `json:"task_parameters"`
	WindowId       string                                          `json:"window_id"`
	MaxErrors      string                                          `json:"max_errors"`
	TaskType       string                                          `json:"task_type"`
	TaskArn        string                                          `json:"task_arn"`
	ServiceRoleArn string                                          `json:"service_role_arn"`
	MaxConcurrency string                                          `json:"max_concurrency"`
	Targets        []AwsSsmMaintenanceWindowTaskSpecTargets        `json:"targets"`
	LoggingInfo    []AwsSsmMaintenanceWindowTaskSpecLoggingInfo    `json:"logging_info"`
}

type AwsSsmMaintenanceWindowTaskSpecTaskParameters struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

type AwsSsmMaintenanceWindowTaskSpecTargets struct {
	Key    string   `json:"key"`
	Values []string `json:"values"`
}

type AwsSsmMaintenanceWindowTaskSpecLoggingInfo struct {
	S3BucketName   string `json:"s3_bucket_name"`
	S3Region       string `json:"s3_region"`
	S3BucketPrefix string `json:"s3_bucket_prefix"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type AwsSsmMaintenanceWindowTaskList struct {
	meta_v1.TypeMeta   `json",inline"`
	meta_v1.ObjectMeta `json"metadata,omitempty"`
	Items              []AwsSsmMaintenanceWindowTask `json"items"`
}
