/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsIamUserLoginProfiles implements AwsIamUserLoginProfileInterface
type FakeAwsIamUserLoginProfiles struct {
	Fake *FakeChronojamV1alpha1
	ns   string
}

var awsiamuserloginprofilesResource = schema.GroupVersionResource{Group: "chronojam.co.uk", Version: "v1alpha1", Resource: "awsiamuserloginprofiles"}

var awsiamuserloginprofilesKind = schema.GroupVersionKind{Group: "chronojam.co.uk", Version: "v1alpha1", Kind: "AwsIamUserLoginProfile"}

// Get takes name of the awsIamUserLoginProfile, and returns the corresponding awsIamUserLoginProfile object, and an error if there is any.
func (c *FakeAwsIamUserLoginProfiles) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsIamUserLoginProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsiamuserloginprofilesResource, c.ns, name), &v1alpha1.AwsIamUserLoginProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamUserLoginProfile), err
}

// List takes label and field selectors, and returns the list of AwsIamUserLoginProfiles that match those selectors.
func (c *FakeAwsIamUserLoginProfiles) List(opts v1.ListOptions) (result *v1alpha1.AwsIamUserLoginProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsiamuserloginprofilesResource, awsiamuserloginprofilesKind, c.ns, opts), &v1alpha1.AwsIamUserLoginProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsIamUserLoginProfileList{}
	for _, item := range obj.(*v1alpha1.AwsIamUserLoginProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsIamUserLoginProfiles.
func (c *FakeAwsIamUserLoginProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsiamuserloginprofilesResource, c.ns, opts))

}

// Create takes the representation of a awsIamUserLoginProfile and creates it.  Returns the server's representation of the awsIamUserLoginProfile, and an error, if there is any.
func (c *FakeAwsIamUserLoginProfiles) Create(awsIamUserLoginProfile *v1alpha1.AwsIamUserLoginProfile) (result *v1alpha1.AwsIamUserLoginProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsiamuserloginprofilesResource, c.ns, awsIamUserLoginProfile), &v1alpha1.AwsIamUserLoginProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamUserLoginProfile), err
}

// Update takes the representation of a awsIamUserLoginProfile and updates it. Returns the server's representation of the awsIamUserLoginProfile, and an error, if there is any.
func (c *FakeAwsIamUserLoginProfiles) Update(awsIamUserLoginProfile *v1alpha1.AwsIamUserLoginProfile) (result *v1alpha1.AwsIamUserLoginProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsiamuserloginprofilesResource, c.ns, awsIamUserLoginProfile), &v1alpha1.AwsIamUserLoginProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamUserLoginProfile), err
}

// Delete takes name of the awsIamUserLoginProfile and deletes it. Returns an error if one occurs.
func (c *FakeAwsIamUserLoginProfiles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsiamuserloginprofilesResource, c.ns, name), &v1alpha1.AwsIamUserLoginProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsIamUserLoginProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsiamuserloginprofilesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsIamUserLoginProfileList{})
	return err
}

// Patch applies the patch and returns the patched awsIamUserLoginProfile.
func (c *FakeAwsIamUserLoginProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsIamUserLoginProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsiamuserloginprofilesResource, c.ns, name, data, subresources...), &v1alpha1.AwsIamUserLoginProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamUserLoginProfile), err
}
