/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsNetworkAclRules implements AwsNetworkAclRuleInterface
type FakeAwsNetworkAclRules struct {
	Fake *FakeChronojamV1alpha1
	ns   string
}

var awsnetworkaclrulesResource = schema.GroupVersionResource{Group: "chronojam.co.uk", Version: "v1alpha1", Resource: "awsnetworkaclrules"}

var awsnetworkaclrulesKind = schema.GroupVersionKind{Group: "chronojam.co.uk", Version: "v1alpha1", Kind: "AwsNetworkAclRule"}

// Get takes name of the awsNetworkAclRule, and returns the corresponding awsNetworkAclRule object, and an error if there is any.
func (c *FakeAwsNetworkAclRules) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsNetworkAclRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsnetworkaclrulesResource, c.ns, name), &v1alpha1.AwsNetworkAclRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsNetworkAclRule), err
}

// List takes label and field selectors, and returns the list of AwsNetworkAclRules that match those selectors.
func (c *FakeAwsNetworkAclRules) List(opts v1.ListOptions) (result *v1alpha1.AwsNetworkAclRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsnetworkaclrulesResource, awsnetworkaclrulesKind, c.ns, opts), &v1alpha1.AwsNetworkAclRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsNetworkAclRuleList{}
	for _, item := range obj.(*v1alpha1.AwsNetworkAclRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsNetworkAclRules.
func (c *FakeAwsNetworkAclRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsnetworkaclrulesResource, c.ns, opts))

}

// Create takes the representation of a awsNetworkAclRule and creates it.  Returns the server's representation of the awsNetworkAclRule, and an error, if there is any.
func (c *FakeAwsNetworkAclRules) Create(awsNetworkAclRule *v1alpha1.AwsNetworkAclRule) (result *v1alpha1.AwsNetworkAclRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsnetworkaclrulesResource, c.ns, awsNetworkAclRule), &v1alpha1.AwsNetworkAclRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsNetworkAclRule), err
}

// Update takes the representation of a awsNetworkAclRule and updates it. Returns the server's representation of the awsNetworkAclRule, and an error, if there is any.
func (c *FakeAwsNetworkAclRules) Update(awsNetworkAclRule *v1alpha1.AwsNetworkAclRule) (result *v1alpha1.AwsNetworkAclRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsnetworkaclrulesResource, c.ns, awsNetworkAclRule), &v1alpha1.AwsNetworkAclRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsNetworkAclRule), err
}

// Delete takes name of the awsNetworkAclRule and deletes it. Returns an error if one occurs.
func (c *FakeAwsNetworkAclRules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsnetworkaclrulesResource, c.ns, name), &v1alpha1.AwsNetworkAclRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsNetworkAclRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsnetworkaclrulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsNetworkAclRuleList{})
	return err
}

// Patch applies the patch and returns the patched awsNetworkAclRule.
func (c *FakeAwsNetworkAclRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsNetworkAclRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsnetworkaclrulesResource, c.ns, name, data, subresources...), &v1alpha1.AwsNetworkAclRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsNetworkAclRule), err
}
