/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsIamAccessKeys implements AwsIamAccessKeyInterface
type FakeAwsIamAccessKeys struct {
	Fake *FakeChronojamV1alpha1
	ns   string
}

var awsiamaccesskeysResource = schema.GroupVersionResource{Group: "chronojam.co.uk", Version: "v1alpha1", Resource: "awsiamaccesskeys"}

var awsiamaccesskeysKind = schema.GroupVersionKind{Group: "chronojam.co.uk", Version: "v1alpha1", Kind: "AwsIamAccessKey"}

// Get takes name of the awsIamAccessKey, and returns the corresponding awsIamAccessKey object, and an error if there is any.
func (c *FakeAwsIamAccessKeys) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsIamAccessKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsiamaccesskeysResource, c.ns, name), &v1alpha1.AwsIamAccessKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamAccessKey), err
}

// List takes label and field selectors, and returns the list of AwsIamAccessKeys that match those selectors.
func (c *FakeAwsIamAccessKeys) List(opts v1.ListOptions) (result *v1alpha1.AwsIamAccessKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsiamaccesskeysResource, awsiamaccesskeysKind, c.ns, opts), &v1alpha1.AwsIamAccessKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsIamAccessKeyList{}
	for _, item := range obj.(*v1alpha1.AwsIamAccessKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsIamAccessKeys.
func (c *FakeAwsIamAccessKeys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsiamaccesskeysResource, c.ns, opts))

}

// Create takes the representation of a awsIamAccessKey and creates it.  Returns the server's representation of the awsIamAccessKey, and an error, if there is any.
func (c *FakeAwsIamAccessKeys) Create(awsIamAccessKey *v1alpha1.AwsIamAccessKey) (result *v1alpha1.AwsIamAccessKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsiamaccesskeysResource, c.ns, awsIamAccessKey), &v1alpha1.AwsIamAccessKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamAccessKey), err
}

// Update takes the representation of a awsIamAccessKey and updates it. Returns the server's representation of the awsIamAccessKey, and an error, if there is any.
func (c *FakeAwsIamAccessKeys) Update(awsIamAccessKey *v1alpha1.AwsIamAccessKey) (result *v1alpha1.AwsIamAccessKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsiamaccesskeysResource, c.ns, awsIamAccessKey), &v1alpha1.AwsIamAccessKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamAccessKey), err
}

// Delete takes name of the awsIamAccessKey and deletes it. Returns an error if one occurs.
func (c *FakeAwsIamAccessKeys) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsiamaccesskeysResource, c.ns, name), &v1alpha1.AwsIamAccessKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsIamAccessKeys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsiamaccesskeysResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsIamAccessKeyList{})
	return err
}

// Patch applies the patch and returns the patched awsIamAccessKey.
func (c *FakeAwsIamAccessKeys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsIamAccessKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsiamaccesskeysResource, c.ns, name, data, subresources...), &v1alpha1.AwsIamAccessKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsIamAccessKey), err
}
