/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsVpcEndpoints implements AwsVpcEndpointInterface
type FakeAwsVpcEndpoints struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var awsvpcendpointsResource = schema.GroupVersionResource{Group: "aws", Version: "v1alpha1", Resource: "awsvpcendpoints"}

var awsvpcendpointsKind = schema.GroupVersionKind{Group: "aws", Version: "v1alpha1", Kind: "AwsVpcEndpoint"}

// Get takes name of the awsVpcEndpoint, and returns the corresponding awsVpcEndpoint object, and an error if there is any.
func (c *FakeAwsVpcEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsVpcEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsvpcendpointsResource, c.ns, name), &v1alpha1.AwsVpcEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsVpcEndpoint), err
}

// List takes label and field selectors, and returns the list of AwsVpcEndpoints that match those selectors.
func (c *FakeAwsVpcEndpoints) List(opts v1.ListOptions) (result *v1alpha1.AwsVpcEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsvpcendpointsResource, awsvpcendpointsKind, c.ns, opts), &v1alpha1.AwsVpcEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsVpcEndpointList{}
	for _, item := range obj.(*v1alpha1.AwsVpcEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsVpcEndpoints.
func (c *FakeAwsVpcEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsvpcendpointsResource, c.ns, opts))

}

// Create takes the representation of a awsVpcEndpoint and creates it.  Returns the server's representation of the awsVpcEndpoint, and an error, if there is any.
func (c *FakeAwsVpcEndpoints) Create(awsVpcEndpoint *v1alpha1.AwsVpcEndpoint) (result *v1alpha1.AwsVpcEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsvpcendpointsResource, c.ns, awsVpcEndpoint), &v1alpha1.AwsVpcEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsVpcEndpoint), err
}

// Update takes the representation of a awsVpcEndpoint and updates it. Returns the server's representation of the awsVpcEndpoint, and an error, if there is any.
func (c *FakeAwsVpcEndpoints) Update(awsVpcEndpoint *v1alpha1.AwsVpcEndpoint) (result *v1alpha1.AwsVpcEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsvpcendpointsResource, c.ns, awsVpcEndpoint), &v1alpha1.AwsVpcEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsVpcEndpoint), err
}

// Delete takes name of the awsVpcEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeAwsVpcEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsvpcendpointsResource, c.ns, name), &v1alpha1.AwsVpcEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsVpcEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsvpcendpointsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsVpcEndpointList{})
	return err
}

// Patch applies the patch and returns the patched awsVpcEndpoint.
func (c *FakeAwsVpcEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsVpcEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsvpcendpointsResource, c.ns, name, data, subresources...), &v1alpha1.AwsVpcEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsVpcEndpoint), err
}
