/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsMqBrokers implements AwsMqBrokerInterface
type FakeAwsMqBrokers struct {
	Fake *FakeChronojamV1alpha1
	ns   string
}

var awsmqbrokersResource = schema.GroupVersionResource{Group: "chronojam.co.uk", Version: "v1alpha1", Resource: "awsmqbrokers"}

var awsmqbrokersKind = schema.GroupVersionKind{Group: "chronojam.co.uk", Version: "v1alpha1", Kind: "AwsMqBroker"}

// Get takes name of the awsMqBroker, and returns the corresponding awsMqBroker object, and an error if there is any.
func (c *FakeAwsMqBrokers) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsMqBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsmqbrokersResource, c.ns, name), &v1alpha1.AwsMqBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsMqBroker), err
}

// List takes label and field selectors, and returns the list of AwsMqBrokers that match those selectors.
func (c *FakeAwsMqBrokers) List(opts v1.ListOptions) (result *v1alpha1.AwsMqBrokerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsmqbrokersResource, awsmqbrokersKind, c.ns, opts), &v1alpha1.AwsMqBrokerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsMqBrokerList{}
	for _, item := range obj.(*v1alpha1.AwsMqBrokerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsMqBrokers.
func (c *FakeAwsMqBrokers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsmqbrokersResource, c.ns, opts))

}

// Create takes the representation of a awsMqBroker and creates it.  Returns the server's representation of the awsMqBroker, and an error, if there is any.
func (c *FakeAwsMqBrokers) Create(awsMqBroker *v1alpha1.AwsMqBroker) (result *v1alpha1.AwsMqBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsmqbrokersResource, c.ns, awsMqBroker), &v1alpha1.AwsMqBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsMqBroker), err
}

// Update takes the representation of a awsMqBroker and updates it. Returns the server's representation of the awsMqBroker, and an error, if there is any.
func (c *FakeAwsMqBrokers) Update(awsMqBroker *v1alpha1.AwsMqBroker) (result *v1alpha1.AwsMqBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsmqbrokersResource, c.ns, awsMqBroker), &v1alpha1.AwsMqBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsMqBroker), err
}

// Delete takes name of the awsMqBroker and deletes it. Returns an error if one occurs.
func (c *FakeAwsMqBrokers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsmqbrokersResource, c.ns, name), &v1alpha1.AwsMqBroker{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsMqBrokers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsmqbrokersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsMqBrokerList{})
	return err
}

// Patch applies the patch and returns the patched awsMqBroker.
func (c *FakeAwsMqBrokers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsMqBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsmqbrokersResource, c.ns, name, data, subresources...), &v1alpha1.AwsMqBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsMqBroker), err
}
