
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsautoscalinggroups.chronojam.co.uk
spec:
  group: chronojam.co.uk
  version: v1alpha1
  names:
    kind: AwsAutoscalingGroup
    plural: awsautoscalinggroups
  scope: Namespaced

