
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsautoscalinglifecyclehooks.chronojam.co.uk
spec:
  group: chronojam.co.uk
  version: v1alpha1
  names:
    kind: AwsAutoscalingLifecycleHook
    plural: awsautoscalinglifecyclehooks
  scope: Namespaced

