
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsdefaultsecuritygroups.chronojam.co.uk
spec:
  group: chronojam.co.uk
  version: v1alpha1
  names:
    kind: AwsDefaultSecurityGroup
    plural: awsdefaultsecuritygroups
  scope: Namespaced

