
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awssecuritygrouprules.chronojam.co.uk
spec:
  group: chronojam.co.uk
  version: v1alpha1
  names:
    kind: AwsSecurityGroupRule
    plural: awssecuritygrouprules
  scope: Namespaced

