// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsWafregionalRuleGroupResource struct {
	Resource v1alpha1.AwsWafregionalRuleGroupSpec `json:"aws_wafregional_rule_group"`
}
