// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsSsmAssociationResource struct {
	Resource v1alpha1.AwsSsmAssociationSpec `json:"aws_ssm_association"`
}
