// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsEbsVolumeResource struct {
	Resource v1alpha1.AwsEbsVolumeSpec `json:"aws_ebs_volume"`
}
