// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsLbListenerCertificateResource struct {
	Resource v1alpha1.AwsLbListenerCertificateSpec `json:"aws_lb_listener_certificate"`
}
