// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsBatchJobDefinitionResource struct {
	Resource v1alpha1.AwsBatchJobDefinitionSpec `json:"aws_batch_job_definition"`
}
