// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsOpsworksRailsAppLayerResource struct {
	Resource v1alpha1.AwsOpsworksRailsAppLayerSpec `json:"aws_opsworks_rails_app_layer"`
}
