// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsElasticsearchDomainResource struct {
	Resource v1alpha1.AwsElasticsearchDomainSpec `json:"aws_elasticsearch_domain"`
}
