// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsPlacementGroupResource struct {
	Resource v1alpha1.AwsPlacementGroupSpec `json:"aws_placement_group"`
}
