// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsS3BucketMetricResource struct {
	Resource v1alpha1.AwsS3BucketMetricSpec `json:"aws_s3_bucket_metric"`
}
