// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsLightsailInstanceResource struct {
	Resource v1alpha1.AwsLightsailInstanceSpec `json:"aws_lightsail_instance"`
}
