// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsVpnGatewayRoutePropagationResource struct {
	Resource v1alpha1.AwsVpnGatewayRoutePropagationSpec `json:"aws_vpn_gateway_route_propagation"`
}
