// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsIamAccessKeyResource struct {
	Resource v1alpha1.AwsIamAccessKeySpec `json:"aws_iam_access_key"`
}
