// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsRedshiftSubnetGroupResource struct {
	Resource v1alpha1.AwsRedshiftSubnetGroupSpec `json:"aws_redshift_subnet_group"`
}
