// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsVpcEndpointServiceResource struct {
	Resource v1alpha1.AwsVpcEndpointServiceSpec `json:"aws_vpc_endpoint_service"`
}
