// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsOpsworksApplicationResource struct {
	Resource v1alpha1.AwsOpsworksApplicationSpec `json:"aws_opsworks_application"`
}
