// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsSpotFleetRequestResource struct {
	Resource v1alpha1.AwsSpotFleetRequestSpec `json:"aws_spot_fleet_request"`
}
