// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsRoute53QueryLogResource struct {
	Resource v1alpha1.AwsRoute53QueryLogSpec `json:"aws_route53_query_log"`
}
