// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsCodecommitRepositoryResource struct {
	Resource v1alpha1.AwsCodecommitRepositorySpec `json:"aws_codecommit_repository"`
}
