// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsSnapshotCreateVolumePermissionResource struct {
	Resource v1alpha1.AwsSnapshotCreateVolumePermissionSpec `json:"aws_snapshot_create_volume_permission"`
}
