// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsIamRolePolicyAttachmentResource struct {
	Resource v1alpha1.AwsIamRolePolicyAttachmentSpec `json:"aws_iam_role_policy_attachment"`
}
