// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsSnsTopicSubscriptionResource struct {
	Resource v1alpha1.AwsSnsTopicSubscriptionSpec `json:"aws_sns_topic_subscription"`
}
