// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsLoadBalancerBackendServerPolicyResource struct {
	Resource v1alpha1.AwsLoadBalancerBackendServerPolicySpec `json:"aws_load_balancer_backend_server_policy"`
}
