// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsDbSecurityGroupResource struct {
	Resource v1alpha1.AwsDbSecurityGroupSpec `json:"aws_db_security_group"`
}
