// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsCognitoIdentityPoolResource struct {
	Resource v1alpha1.AwsCognitoIdentityPoolSpec `json:"aws_cognito_identity_pool"`
}
