// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsOpsworksMemcachedLayerResource struct {
	Resource v1alpha1.AwsOpsworksMemcachedLayerSpec `json:"aws_opsworks_memcached_layer"`
}
