// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsWafregionalXssMatchSetResource struct {
	Resource v1alpha1.AwsWafregionalXssMatchSetSpec `json:"aws_wafregional_xss_match_set"`
}
