// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsAthenaNamedQueryResource struct {
	Resource v1alpha1.AwsAthenaNamedQuerySpec `json:"aws_athena_named_query"`
}
