// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsSsmResourceDataSyncResource struct {
	Resource v1alpha1.AwsSsmResourceDataSyncSpec `json:"aws_ssm_resource_data_sync"`
}
