// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsCloudwatchEventTargetResource struct {
	Resource v1alpha1.AwsCloudwatchEventTargetSpec `json:"aws_cloudwatch_event_target"`
}
