// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsEipAssociationResource struct {
	Resource v1alpha1.AwsEipAssociationSpec `json:"aws_eip_association"`
}
