// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsWafWebAclResource struct {
	Resource v1alpha1.AwsWafWebAclSpec `json:"aws_waf_web_acl"`
}
