// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsDbOptionGroupResource struct {
	Resource v1alpha1.AwsDbOptionGroupSpec `json:"aws_db_option_group"`
}
