// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsVpcDhcpOptionsResource struct {
	Resource v1alpha1.AwsVpcDhcpOptionsSpec `json:"aws_vpc_dhcp_options"`
}
