// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsMainRouteTableAssociationResource struct {
	Resource v1alpha1.AwsMainRouteTableAssociationSpec `json:"aws_main_route_table_association"`
}
