// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsEfsMountTargetResource struct {
	Resource v1alpha1.AwsEfsMountTargetSpec `json:"aws_efs_mount_target"`
}
