// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsApiGatewayAuthorizerResource struct {
	Resource v1alpha1.AwsApiGatewayAuthorizerSpec `json:"aws_api_gateway_authorizer"`
}
