// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsSesConfigurationSetResource struct {
	Resource v1alpha1.AwsSesConfigurationSetSpec `json:"aws_ses_configuration_set"`
}
