// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsDefaultNetworkAclResource struct {
	Resource v1alpha1.AwsDefaultNetworkAclSpec `json:"aws_default_network_acl"`
}
