// GENERATED BY TF-GENERATOR, DO NOT EDIT.

package v1alpha1

import (
	"github.com/chronojam/terraform-operator/pkg/apis/aws/v1alpha1"
)

type AwsCloudwatchLogMetricFilterResource struct {
	Resource v1alpha1.AwsCloudwatchLogMetricFilterSpec `json:"aws_cloudwatch_log_metric_filter"`
}
